### ISSUE TITLE
Add KrakenUniq

### ISSUE THREAD

**Issue by mjamy** [nf-core/taxprofiler#102]
### Description of feature

Classifies short- and long-reads using unique k-mer counts.

**Comment by jfy133** [comment]
Suggested as a possibility for long reads in https://www.sciencedirect.com/science/article/pii/S2001037021000714https://www.sciencedirect.com/science/article/pii/S2001037021000714 [^1]

[^1] https://nfcore.slack.com/archives/C031QH57DSS/p1657629452756179
