### ISSUE TITLE
Update configs for test profile and test_noprofiling

### ISSUE THREAD

**Issue by sofstam** [nf-core/taxprofiler#108]
### Description of the bug

When executing the test profile with the following arguments:

`nextflow run nf-core/taxprofiler -r dev --outdir test_filtlong  --perform_shortread_qc=false --run_kaiju=false --run_metaphlan3=false --run_diamond=false --perform_shortread_complexityfilter=false -profile hasta,dev_prio,test,singularity`

we get the following warning: 

<img width="1057" alt="Screenshot 2022-07-26 at 09 52 33" src="https://user-images.githubusercontent.com/91951607/180959081-a8176f0d-c86d-430e-8ff8-7cc15b0a1749.png">

We need to update the configs so that `filtlong` is executed as well.

**Comment by jfy133** [comment]
At least when I run the command myself I don't get the error!
