### ISSUE TITLE
Postprocessing: bracken

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#12]
### Description of feature

Bracken (Bayesian Reestimation of Abundance with KrakEN) is a highly accurate statistical method that computes the abundance of species in DNA sequences from a metagenomics sample. Braken uses the taxonomy labels assigned by [Kraken](https://ccb.jhu.edu/software/kraken/), a highly accurate metagenomics classification algorithm, to estimate the number of reads originating from each species present in a sample. Kraken classifies reads to the best matching location in the taxonomic tree, but does not estimate abundances of species. We use the Kraken database itself to derive probabilities that describe how much sequence from each genome is identical to other genomes in the database, and combine this information with the assignments for a particular sample to estimate abundance at the species level, the genus level, or above. Combined with the Kraken classifier, Bracken produces accurate species- and genus-level abundance estimates even when a sample contains two or more near-identical species.

https://ccb.jhu.edu/software/bracken/

**Comment by jfy133** [comment]
@Midnighter I was just wondering, this would be nice, but I was wondering if it would be necessary for the first release as it's a 'downstream' step after the classification. What do you think?

**Comment by Midnighter** [comment]
Not strictly necessary, no, but I don't think it would take me long to add.
