### ISSUE TITLE
Classifier for Nanopore reads: BugSeq-V2

### ISSUE THREAD

**Issue by sofstam** [nf-core/taxprofiler#121]
Also, this may be out-of-scope until after a stable release, but a bespoke implementation of BugSeq-V2 seems worth investigating given its performance in that preprint.

_Originally posted by @gregmedlock in https://github.com/nf-core/taxprofiler/issues/22#issuecomment-1072458081_

**Comment by sofstam** [comment]
Since this is a GUI tool, we shall consider it as a candidate for nanopore in upcoming releases instead.

**Comment by jfy133** [comment]
It's a web online platform, so I doln't think it'll ever be possible
