### ISSUE TITLE
centrifuge_kreport is failing for test profile

### ISSUE THREAD

**Issue by sofstam** [nf-core/taxprofiler#129]
### Description of the bug

When running taxprofiler with `test` profile, `centrifuge_kreport` is failing for some samples.

**Comment by jfy133** [comment]
When a sample has no hits, CENTRIFUGE exits with exit code 255. 

This is already provided as a `WARN` for us, and doesn't fail the pipeline, so I don't think we need to make any change here

**Comment by jfy133** [comment]
Although we should add documentation in `usage.md`. @sofstam do ou want to take that on? Something like an `FAQ` section or similar

**Comment by jfy133** [comment]
https://github.com/nf-core/taxprofiler/pull/131
