### ISSUE TITLE
Test data for centrifuge

### ISSUE THREAD

**Issue by sofstam** [nf-core/taxprofiler#132]
### Description of feature

We need better test data for centrifuge as process `centrifuge_kreport` gives exit code `255` with the available test dataset when testing with `-profile test`

**Comment by jfy133** [comment]
This is because centrifuge aligns no reads against the minigut_cf database

maybe we need a better centrifuge database instead actually :thinking: that should easier actually!

**Comment by jfy133** [comment]
Done https://github.com/nf-core/test-datasets/pull/614
