### ISSUE TITLE
The output is bad

### ISSUE THREAD

**Issue by luozhy88** [nf-core/taxprofiler#134]
### Description of feature

I had a bad experience about the experience . I hope this process can have a summary of each part.for example, if you run a kraken2,you can get the bundance of tax for each sample in one table.
<img width="398" alt="image" src="https://user-images.githubusercontent.com/94740863/190269498-8bda86b0-43dd-40d0-9311-b2264bb1f692.png">

centrifuge
└── db3
    ├── 2612_se-db3.centrifuge.mapped.fastq.gz
    ├── 2612_se-db3.centrifuge.report.txt
    ├── 2612_se-db3.centrifuge.results.txt
    ├── 2612_se-db3.centrifuge.txt
    ├── 2612_se-db3.centrifuge.unmapped.fastq.gz
    ├── 2613_se-db3.centrifuge.mapped.fastq.gz
    ├── 2613_se-db3.centrifuge.report.txt
    ├── 2613_se-db3.centrifuge.results.txt
    ├── 2613_se-db3.centrifuge.txt
    ├── 2613_se-db3.centrifuge.unmapped.fastq.gz
    ├── ERR3201952_se-db3.centrifuge.mapped.fastq.gz
    ├── ERR3201952_se-db3.centrifuge.report.txt
    ├── ERR3201952_se-db3.centrifuge.results.txt
    ├── ERR3201952_se-db3.centrifuge.txt
    └── ERR3201952_se-db3.centrifuge.unmapped.fastq.gz
diamond
└── db1
    ├── 2611_se-db1.log
    ├── 2611_se-db1.sam
    ├── 2612_se-db1.log
    ├── 2612_se-db1.sam
    ├── 2613_se-db1.log
    ├── 2613_se-db1.sam
    ├── ERR3201952_se-db1.log
    └── ERR3201952_se-db1.sam
fastqc
├── processed
│   ├── 2612_ERR5766176_B_processed_fastqc.html
│   ├── 2612_ERR5766176_processed_fastqc.html
│   ├── 2612_ERR5766180_processed_fastqc.html
│   ├── 2613_ERR5766181_processed_fastqc.html
│   └── ERR3201952_ERR3201952_processed_fastqc.html
└── raw
    ├── 2612_ERR5766176_B_raw_1_fastqc.html
    ├── 2612_ERR5766176_B_raw_2_fastqc.html
    ├── 2612_ERR5766176_raw_1_fastqc.html
    ├── 2612_ERR5766176_raw_2_fastqc.html
    ├── 2612_ERR5766180_raw_fastqc.html
    ├── 2613_ERR5766181_raw_1_fastqc.html
    ├── 2613_ERR5766181_raw_2_fastqc.html
    └── ERR3201952_ERR3201952_raw_fastqc.html
kaiju
└── db5
    ├── 2611_se-db5.tsv
    ├── 2612_se-db5.tsv
    ├── 2613_se-db5.tsv
    └── ERR3201952_se-db5.tsv
kraken2
├── db1
│   ├── 2611_se-db1.classified.fastq.gz
│   ├── 2611_se-db1.kraken2.report.txt
│   ├── 2611_se-db1.unclassified.fastq.gz
│   ├── 2612_se-db1.classified.fastq.gz
│   ├── 2612_se-db1.kraken2.report.txt
│   ├── 2612_se-db1.unclassified.fastq.gz
│   ├── 2613_se-db1.classified.fastq.gz
│   ├── 2613_se-db1.kraken2.report.txt
│   ├── 2613_se-db1.unclassified.fastq.gz
│   ├── ERR3201952_se-db1.classified.fastq.gz
│   ├── ERR3201952_se-db1.kraken2.report.txt
│   └── ERR3201952_se-db1.unclassified.fastq.gz
└── db2
    ├── 2611_se-db2.classified.fastq.gz
    ├── 2611_se-db2.kraken2.report.txt
    ├── 2611_se-db2.unclassified.fastq.gz
    ├── 2612_se-db2.classified.fastq.gz
    ├── 2612_se-db2.kraken2.report.txt
    ├── 2612_se-db2.unclassified.fastq.gz
    ├── 2613_se-db2.classified.fastq.gz
    ├── 2613_se-db2.kraken2.report.txt
    ├── 2613_se-db2.unclassified.fastq.gz
    ├── ERR3201952_se-db2.classified.fastq.gz
    ├── ERR3201952_se-db2.kraken2.report.txt
    └── ERR3201952_se-db2.unclassified.fastq.gz
krona
├── centrifuge-db3.html
├── kaiju-db5.html
├── kraken2-db1.html
├── kraken2-db2.html
├── malt-malt85.html
└── malt-malt95.html
malt
├── malt85
│   ├── 2612.merged.blastn.sam
│   ├── 2612.merged.rma6
│   ├── 2612.merged.txt.gz
│   ├── 2613_ERR5766181.unmapped.blastn.sam
│   ├── 2613_ERR5766181.unmapped.rma6
│   ├── 2613_ERR5766181.unmapped.txt.gz
│   ├── ERX5474930_ERR5766174_1.blastn.sam
│   ├── ERX5474930_ERR5766174_1.rma6
│   ├── ERX5474930_ERR5766174_1.txt.gz
│   └── malt85-malt-run.log
└── malt95
    ├── 2612.merged.blastn.sam
    ├── 2612.merged.rma6
    ├── 2612.merged.txt.gz
    ├── 2613_ERR5766181.unmapped.blastn.sam
    ├── 2613_ERR5766181.unmapped.rma6
    ├── 2613_ERR5766181.unmapped.txt.gz
    ├── ERX5474930_ERR5766174_1.blastn.sam
    ├── ERX5474930_ERR5766174_1.rma6
    ├── ERX5474930_ERR5766174_1.txt.gz
    └── malt95-malt-run.log
metaphlan3
└── db4
    ├── 2612_se-db4.biom
    ├── 2612_se-db4.bowtie2out.txt
    ├── 2612_se-db4_profile.txt
    ├── 2613_se-db4.biom
    ├── 2613_se-db4.bowtie2out.txt
    ├── 2613_se-db4_profile.txt
    ├── ERR3201952_se-db4.biom
    ├── ERR3201952_se-db4.bowtie2out.txt
    └── ERR3201952_se-db4_profile.txt

**Comment by jfy133** [comment]
Hi @luozhy88 ,

Thanks for interest in the pipeline! Please note that the development of pipeline is still not finished (we have no releases yet: http://nf-co.re/taxprofiler,  https://github.com/nf-core/taxprofiler/releases)

That said, I apologise for the diagram being slightly misleading - this shows the 'final' version of the pipeline (for example, bracken and KrakenUniq are also not yet added to the pipeline).

However the TSV output you indicate is almost there, for example see this pull request: https://github.com/nf-core/taxprofiler/pull/130

If you try again in about a month you will find the pipeline includes the TSVs

Apologies again, and I thank you for your patience.

**Comment by jfy133** [comment]
@luozhy88 If it covers the tools you're interested, all the the currently implemented tools (except DIAMOND and MALT) now produce the final 'TSVs' (albiet in slightly different formats, depending on the tool), so you could try again now.
