### ISSUE TITLE
Remove patch for minimap

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#140]
### Description of the bug

A meta map was added in a module update, but we had to patch it back to the older version during template merge. 

https://github.com/nf-core/taxprofiler/pull/138#discussion_r990291004

We should update the code to use the 'native' version'.

**Comment by Midnighter** [comment]
> A meta map was added in a module update, but we had to patch it back to the older version during template merge.

Just to clarify, we are using the latest module but I patched the input and output to use the simpler format.
