### ISSUE TITLE
Input CSV structure

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#15]
### Description of feature

We will need to support both input (paired/single) FASTQ and also FASTA files, as the latter seems common.

I propose something like this:

```
sample_id,run_id,format,r1,r2
ERS0000001,ERR000008,fasta,/path/to/data1.fa,NA
ERS0000001,ERR000009,fastq,/path/to/data2_1.fq.gz,/path/to/data2_2.fq.gz
ERS0000001,ERR000009,fastq,/path/to/data3_1.fq.gz,NA
```

i.e.

UPDATE: 
|sample|run_accession|instrument_platform|fastq_1|fastq_2|fasta|
|-------------|---------|-------|--|--|--|
|ERS0000001|ERR000008|OXFORD_NANOPORE|NA|NA|/path/to/data1.fa|NA|
|ERS0000001|ERR000009|ILLUMINA|/path/to/data2_1.fq.gz|/path/to/data2_2.fq.gz|
|ERS0000001|ERR000009|ILLUMINA|/path/to/data3_1.fq.gz|NA|

Check `instrument_platform` against: https://www.ebi.ac.uk/ena/portal/api/controlledVocab?field=instrument_platform

**Comment by Midnighter** [comment]
I would use as the input format what is spit out by https://github.com/nf-core/fetchngs so it generally has the same columns but different headers for it. I would drop the format column. If needed, that can be figured out from the filenames.

**Comment by jfy133** [comment]
OK actually I agree, that's what I actually based this off of. Do you have an example of a fetchngs sheet?

**Comment by Midnighter** [comment]
Yeah, it adds a lot of columns but we can pick the ones we need. I do think it's nice, though, if the pipeline keeps all input columns. This makes it easier for users to add any kind of meta information that they would like. The minimal information, in my opinion, is:

```
sample,fastq_1,fastq_2
```

**Comment by maxulysse** [comment]
@jfy133 I think this is csv and not tsv

**Comment by Midnighter** [comment]
CSV seems to be the standard in nf-core pipelines. In Python it's quite easy to allow both but that's harder in nextflow I think.

**Comment by maxulysse** [comment]
not at all, you have the `splitCsv` operator: https://www.nextflow.io/docs/latest/operator.html#splitcsv

**Comment by Midnighter** [comment]
Yes, but it cannot "sniff" it's CSV or TSV, so you either need to hard code it, look at the file extension, or let the user determine it.

**Comment by maxulysse** [comment]
Oh I see what you mean, then yes you're right.
And as you said, csv is the standard in DSL2 nf-core pipelines.

**Comment by jfy133** [comment]
Sorry yup - eager is TSV :sweat_smile:

**Comment by maxulysse** [comment]
Sarek was TSV too, we're now csv

**Comment by jfy133** [comment]
Don't abanon me!

Back on topic:

accept: fastq, fq, fasta, fna. fa + all with `.gz`

**Comment by jfy133** [comment]
@maxibor  decided to go for an explicit `.fasta` column as this means `fastq_1` and `fastq_2 can be taken directly from fetchNGS

**Comment by Midnighter** [comment]
> should change platform to specific machine, as we need 2/4 colour chemsity info

Can you provide some more context, please, why this is needed?

**Comment by jfy133** [comment]
https://support.illumina.com/content/dam/illumina-support/help/Illumina_DRAGEN_Bio_IT_Platform_v3_7_1000000141465/Content/SW/Informatics/Dragen/PolyG_Trimming_fDG.htm

**Comment by jfy133** [comment]
@maxibor did you add a check that if you can't supply FASTA and FASTQ in the same line?

**Comment by jfy133** [comment]
I think this is set for now, can reopen if more issues crop up
