### ISSUE TITLE
Convert samtools stats into subworkflow(s)

### ISSUE THREAD

**Issue by Midnighter** [nf-core/taxprofiler#166]
It'd be great to have a general samtools stats subworkflow on nf-core/modules that we then install here. And then use it for both long and short reads.

_Originally posted by @sofstam in https://github.com/nf-core/taxprofiler/issues/162#issuecomment-1296978513_

**Comment by Midnighter** [comment]
I don't think this needs to be in the first release milestone. It's a nice-to-have.

**Comment by sofstam** [comment]
https://github.com/nf-core/modules/tree/master/subworkflows/nf-core/bam_stats_samtools

This has already been implemented so I can update taxprofiler.

**Comment by jfy133** [comment]
after reviewing the code, we decided it would be too much overhead to convert to a subworkflow (a whole subworkflow for only two modules and one join; where my personal rule of thumb is 3 or more steps consistutes a subworkflow). Therefore we close this.
