### ISSUE TITLE
Should we disable Bracken for long read data?

### ISSUE THREAD

**Issue by Midnighter** [nf-core/taxprofiler#167]
### Description of feature

Bracken expects a specific read length as input for which a database has to be preconstructed. Long reads (especially ONT) are typically quite variable in size, making it hard to decide on such a read length. Additionally, I would assume that the longer reads  are very specific to one particular reference genome such that maybe post-processing by Bracken is not needed at all.

Maybe we should disable Bracken for long reads?

**Comment by Midnighter** [comment]
See also https://github.com/jenniferlu717/Bracken/issues/60

**Comment by jfy133** [comment]
ok, we are getting test failures for bracken because the long reads for `ERR3201952` (our nanopore/long read test file) fail to be assigned by Kraken, (so Krakcen reports all reads unclassified), and then Bracken dies.

So I'm going to say yes, so will make a PR for this now

**Comment by Midnighter** [comment]
Didn't I set the default `errorStrategy` for Bracken to `'ignore'` already which should cover that?

**Comment by jfy133** [comment]
Yes, but it it means that our tests don't finish 'nicely' so I would rather disable it entirely as it's still an open question
