### ISSUE TITLE
Make Bracken parametrization possible

### ISSUE THREAD

**Issue by Midnighter** [nf-core/taxprofiler#168]
### Description of the bug

At the moment there is no way to insert the Bracken parameters into the `meta` map. This needs to be addressed by either inserting or refactoring the Bracken module to work differently. Bracken can be used, configured with `ext.args` but only for single parameter values.

**Comment by jfy133** [comment]
What do you mean no way to insert the Brakcen parameters into the meta map? These should be derived from the input database sheet, no?

**Comment by jfy133** [comment]
Ah looking back I see what you mean... yes, that module is an early one now looking at the nf-core/modules PR. All the `meta.` should be stripped indeed...

**Comment by jfy133** [comment]
Done in https://github.com/nf-core/taxprofiler/pull/183
