### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#18]
### Description of feature

Start writing documentation.

This can include parameters, making a pretty workflow diagram, describing output files etc.

**Comment by jfy133** [comment]
Started work in #50 

TODO: Add to usage some basic explanations of the different preprocessing options.

"Thanks for adding some documentation. I noticed that you use profiling pretty exclusively. Maybe we need to define how we use certain terms, i.e., do we treat profiling, classification, and read mapping as synonyms or not?" from @Midnighter

**Comment by sofstam** [comment]
From slack: review the output docs when taxpasta is in, we should make sure to note down exactly which files go into taxpasta etc. (e.g.,  whether we send count or abundance files to taxpasta - partcuary MP3)
