### ISSUE TITLE
Run untar on DBs of tools actually using

### ISSUE THREAD

**Issue by sofstam** [nf-core/taxprofiler#196]
### Description of feature

Going through ToDos before first release. Shall we filter to only run UNTAR on DBs of tools actually using? Shall we make optional whether to save?

https://github.com/nf-core/taxprofiler/blob/578081df2e38b2de25509e683a13cd3d22ac772a/subworkflows/local/db_check.nf#L40-L50

**Comment by Midnighter** [comment]
I like both ideas:

- [x] filter to untar only DBs that are actually used
- [x] Make saving optional

**Comment by sofstam** [comment]
I added it as a task for the next release if you agree @Midnighter @jfy133

**Comment by jfy133** [comment]
I think it might be straight forward with a simple `filter{}` and (long) condition... (`if ( tool == XYZ && run_xyz || tool == ABC && run abc )` sort of thing... not sure yet how that would be constructed
