### ISSUE TITLE
Update HTML to preferred methods description

### ISSUE THREAD

**Issue by sofstam** [nf-core/taxprofiler#197]
### Description of feature

Going through ToDos before first-release and it would be nice to update the HTML below to your preferred methods description, e.g. add publication citation for this pipeline

https://github.com/nf-core/taxprofiler/blob/ff1670169a86bf59bf99fbc298feb6c65d90e4e2/assets/methods_description_template.yml#L6-L19

**Comment by jfy133** [comment]
Maybe we wait until the publication for this, and to giveme more time to see if we can dynamically include citation info for each tool (an idea I had for funcscan)
