### ISSUE TITLE
Add all file path parameters

### ISSUE THREAD

**Issue by sofstam** [nf-core/taxprofiler#199]
### Description of feature

Going through all ToDos before first-release, it would be good to add all file path parameters for the pipeline to the list below:

https://github.com/nf-core/taxprofiler/blob/578081df2e38b2de25509e683a13cd3d22ac772a/workflows/taxprofiler.nf#L12-L17

**Comment by sofstam** [comment]
Are  `multiqc_title`, `multiqc_logo` and `multiqc_methods_description` path parameters?

**Comment by jfy133** [comment]
logo and methods description is, but these aren't critical

**Comment by jfy133** [comment]
I'll add them anyway now as I had to do a small bug fix
