### ISSUE TITLE
Add Nanopore long reads fastq files as input

### ISSUE THREAD

**Issue by ljmesi** [nf-core/taxprofiler#20]
### Description of feature

At the moment there is only an option to use short reads (Illumina). An additional option to use Nanopore long reads fastq files as input could be added to the workflow.

#### This can be closed when:
- [x] #23
- [x] #25
- [x] #21
- [x] #28
- [x] #69 
- [x] #40 
- [x] #22

**Comment by jfy133** [comment]
@ljmesi do you think it would be necessary to have a host-removal step speicfically for long reads?

**Comment by jfy133** [comment]
As proposed here: https://github.com/nf-core/taxprofiler/issues/40

**Comment by ljmesi** [comment]
@jfy133 Sorry for late response! I've been on a holiday until now. Yes, host-removal with minimap2 would be good to have for long reads.

**Comment by jfy133** [comment]
@sofstam @ljmesi @talnor was there any other long-read/nanopore profilers suggested other than metawrap, whihc looks like it has stalled?

**Comment by jfy133** [comment]
There are no more reported nanopore specific profilers, and metamaps seems to not be getting any updates, so I'll close this for now. We can extent in teh ftuture.
