### ISSUE TITLE
Clarify taxonomic classification vs profiling everywhere

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#211]
### Description of the bug

As suggested by @Midnighter https://nfcore.slack.com/archives/C031QH57DSS/p1673863932137969?thread_ts=1673858047.865519&cid=C031QH57DSS

(i.e. classification - who is there, profiling - how much of who is there)

**Comment by jfy133** [comment]
I see, you mean write a note/big fat warning somewhere explicitly saying you shouldn't consider read-count as equivalent to taxonomic abundance? More of an interpretational note?

**Comment by Midnighter** [comment]
I'm not sure yet how/where to place it but it's critical information, yes.

**Comment by jfy133** [comment]
Ok I'll try a proposal

**Comment by jfy133** [comment]
Could you look at #212 now? I've added something for usage, we should also mention this on output docs but need to wait until that is ready
