### ISSUE TITLE
Nanopore reads are classified with a set of taxonomic profilers

### ISSUE THREAD

**Issue by sofstam** [nf-core/taxprofiler#22]
## Classifiers that can be tested or investigated for nanopore reads:
- [ ] [MetaMaps](https://www.nature.com/articles/s41467-019-10934-2)
- [ ] [MEGAN-LR](https://biologydirect.biomedcentral.com/articles/10.1186/s13062-018-0208-7), further investigation is needed if this tool can be used in the pipeline
- [x] Kraken2
- [x] Centrifuge
    - [x] [centrifuge/centrifuge](https://github.com/nf-core/modules/tree/master/modules/centrifuge/centrifuge) module needs to be added to taxprofiler
    - [x] [centrfuge/kreport](https://github.com/nf-core/modules/tree/master/modules/centrifuge/kreport) module needs to be added to taxprofiler
- [x] Kaiju
     - [x] [kaiju/kaiju](https://github.com/nf-core/modules/tree/master/modules/kaiju/kaiju) module needs to be added to taxprofiler
     - [x] kaiju/kaiju2table module needs to be added to taxprofiler

**Comment by jfy133** [comment]
Note that MEGAN itself is a GUI based tool, and may not be :100: suitable for pipelining (however sometimes some of the functionality is present in utility tools packged with MEGAN, so it may still be possible - I actually plan to include the MEGAN container anyway, as it has a useful tool to convert MALT RMA6 files into tables) - so it's something worth investigating

**Comment by sofstam** [comment]
I was thinking more of investigating MEGAN at this point, I will update the description of the issue.

**Comment by gregmedlock** [comment]
FYI the preprint that @Midnighter linked used PacBio's snakemake workflow for HiFi/nanopore reads with MEGAN-LR, and describes which executable tools + files are used from the MEGAN community edition, so it should be possible : )

Also, this may be out-of-scope until after a stable release, but a bespoke implementation of BugSeq-V2 seems worth investigating given its performance in that preprint.

**Comment by jfy133** [comment]
There doesn't seem to be any further updates from metaMaps so going to close this (sadly)

**Comment by Midnighter** [comment]
If we're closing this issue, can we open two new ones to remember @gregmedlock 's points above https://github.com/nf-core/taxprofiler/issues/22#issuecomment-1072458081

**Comment by jfy133** [comment]
@sofstam could you do that?

**Comment by jfy133** [comment]
note that when I look at the MEGNA-LR related snakemake pipeline, that's just actually minimap2 + a LCA... we could do that instead I guess but it's a whole extra (rather large workflow). Although admittedly with tools we already have in taxprofiler
