### ISSUE TITLE
Split up longread- and short-read parameters in databases

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#226]
### Description of feature

We should somehow allow specifying different profiling parameters depending on whether a database is for short-read or long-read use.

e.g. for bracken, a database of 400bp of short read read length doesn't make sense to run with nanopore data.

Could have a column in the database sheet specifying whether a database is for short- or long-read (or both?), and then only samples for e.g. illumina goes is combined with the short-reads, and samples for e.g. annopore goes with long-read databases

**Comment by sofstam** [comment]
Add extra columns to databases.csv and update the meta.

**Comment by LilyAnderssonLee** [comment]
Fixed in the PR https://github.com/nf-core/taxprofiler/pull/466
