### ISSUE TITLE
Process input to krakenuniq in batches of n samples

### ISSUE THREAD

**Issue by guille0387** [nf-core/taxprofiler#239]
### Description of feature

Currently, taxprofiler's krakenuniq process analyses the input samples one by one using a loop. Perhaps the code may be changed to process the samples in batches of n samples to speed up the overall execution of the pipeline.

**Comment by jfy133** [comment]
Coming to my mind when glancing at this: one issue potentially for batching is if one compute node recieves two reloaded krakenuniq runs at once; can a database be loaded twice into memory or would this lead to some confusion as to which sample should go with which database?

**Comment by guille0387** [comment]
That's a good question @jfy133 .... I don't know if that would be an issue.... I wonder if there's a way one could tell nextflow to submit the jobs from a specific process into different computing nodes?

**Comment by jfy133** [comment]
I'm not aware of such an option unfortuantely, as this mechanism normally has to happen at a scheduler level.

Alternatively we just make an option to use 'standard' krakenuniq instead of preloading...?

**Comment by guille0387** [comment]
I think that's a good idea @jfy133 , at least for now :) Having this option would be great, and I guess mention in the pipeline's documentation when it'd be recommended to use this option (i.e. considering DB size and access to HPC/cloud)

**Comment by jfy133** [comment]
This would have to be in the second release though, as it would require a bit of re-plumbing :\

**Comment by jfy133** [comment]
No no, keep it open for us to address in the future :)
