### ISSUE TITLE
Implement nf-core modules to build dbs from each classifier/profiler

### ISSUE THREAD

**Issue by sofstam** [nf-core/taxprofiler#247]
### Description of feature

Linked to #49 

We need separate modules for db-build:
- [ ] Kraken2 [#2953](https://github.com/nf-core/modules/issues/2953)
- [x] Centrifuge [#2956](https://github.com/nf-core/modules/issues/2956)
- [x] Kaiju [#2955](https://github.com/nf-core/modules/issues/2955)
- [ ] Bracken [#2957](https://github.com/nf-core/modules/issues/2957)
- [x] Metaphlan3 [#2954](https://github.com/nf-core/modules/issues/2954)

**Comment by jfy133** [comment]
Moved to createtaxdb!
