### ISSUE TITLE
Kraken2 prints read classifications to stdout if --output flag is not set 

### ISSUE THREAD

**Issue by prototaxites** [nf-core/taxprofiler#268]
### Description of the bug

Kraken2 prints read classifications to stdout when the `--output` flag is not set. 

This flag currently is only set when `params.kraken2_save_readclassification` is enabled, and thus when this flag is not enabled, the read classifications are still saved to the .command.out file within the work directory. When running with the SLURM scheduler, stdout is also saved to .command.log, resulting in two nearly identical files (.command.log also receives stderr) - I am not sure whether this is the same on other systems. These files can run many Gb in size depending on the size of the input fastq files.

The format of the output is as follows:

```
% head .command.log
Loading database information... done.
U	A00821:985:H5KF5DSX3:1:1101:13051:1047	0	150|150	0:116 |:| 0:16 9606:2 0:98
U	A00821:985:H5KF5DSX3:1:1101:22634:1047	0	150|150	0:116 |:| 0:116
U	A00821:985:H5KF5DSX3:1:1101:23647:1047	0	150|150	0:116 |:| 0:116
U	A00821:985:H5KF5DSX3:1:1101:12861:1063	0	150|150	0:116 |:| 0:116

...read classifications...

% tail .command.log
U	A01426:284:H5CL7DSX3:1:2678:24433:37043	0	150|150	0:116 |:| 0:116
U	A01426:284:H5CL7DSX3:1:2678:25138:37043	0	150|150	0:116 |:| 0:116
U	A01426:284:H5CL7DSX3:1:2678:18005:36839	0	150|150	0:116 |:| 0:116
U	A01426:284:H5CL7DSX3:1:2678:21820:36839	0	150|150	0:116 |:| 0:116
U	A01426:284:H5CL7DSX3:1:2678:27859:36839	0	150|150	0:116 |:| 0:116
U	A01426:284:H5CL7DSX3:1:2678:20021:36855	0	150|150	0:116 |:| 0:116
C	A01426:284:H5CL7DSX3:1:2678:23384:36855	2596916	150|150	0:41 2596916:3 0:35 2884263:5 0:32 |:| 85023:1 0:17 2596916:5 0:75 163604:5 0:13
19222944 sequences (5755.17 Mbp) processed in 260.791s (4422.6 Kseq/m, 1324.09 Mbp/m).
  1077232 sequences classified (5.60%)
  18145712 sequences unclassified (94.40%)
```

Disk usage statistics:
```
% du -hs * .*
0	FO5_1.fq.gz
0	FO5_2.fq.gz
0	kraken2
636K	Leaf_FO5_pe_Leaf_FO5_kraken2.kraken2.kraken2.report.txt
4.0K	versions.yml
0	.command.begin
4.0K	.command.err
1.3G	.command.log
1.3G	.command.out
12K	.command.run
4.0K	.command.sh
4.0K	.command.trace
4.0K	.exitcode
```

A possible fix could be to redirect stdout to /dev/null in the module code when `params.kraken2_save_readclassification` is not set, or setting --output directly to /dev/null. The information about sequence classification percentages is written to stderr and thus also goes to .command.err, so redirection shouldn't be a problem here.

### Command used and terminal output

```console
nextflow run nf-core/taxprofiler \
    -resume \
    -r 1.0.0 \
    -profile scw \
    --input "inputs/samples.csv" \
    --databases "inputs/databases.csv" \
    --run_kraken2 \
    --run_profile_standardisation \
    --outdir "results/"
```

**Comment by Midnighter** [comment]
I did some digging and I come to the same conclusion: redirecting output to `/dev/null` seems the best solution.

**Comment by prototaxites** [comment]
Was looking at running KrakenUniq on my data as well, and it looks like this module has the same problem going by the KrakenUniq docs:

https://github.com/nf-core/taxprofiler/blob/master/modules/nf-core/krakenuniq/preloadedkrakenuniq/main.nf:
```
    def output_option = save_output ? '--output "\${PREFIX}.krakenuniq.classified.txt"' : ''
```

https://github.com/fbreitwieser/krakenuniq:
```
  --output FILENAME       Print output to filename (default: stdout); "off" will
                          suppress normal output
```

**Comment by Midnighter** [comment]
Good find! Now I'm wondering about Bracken, too.
