### ISSUE TITLE
New profiler: MetaPhlAn4

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#273]
### Description of feature

https://www.nature.com/articles/s41587-023-01688-w

**Comment by LilyAnderssonLee** [comment]
Should I create a new 'metaphlan' module or update the existing 'metaphlan3' module? @jfy133

**Comment by jfy133** [comment]
Good question, I think with @Midnighter we said we would make a new module called _just_ `metaphlan` which is what all future versions would come under (so `metaphlan` for versions 4,5,6 etc.

**Comment by jfy133** [comment]
Basically to match whatever is in bioconda :)

**Comment by LilyAnderssonLee** [comment]
Great! Then I will add my new module as metaphlan/makedb.

**Comment by LilyAnderssonLee** [comment]
I think we can close this issue now. I have added the "metaphlan" module.

**Comment by sofstam** [comment]
It has to be added to taxprofiler's workflow as well so I will reopen the issue :)

**Comment by flashton2003** [comment]
Hi, would be great to have metaphlan4 available within taxprofiler :-D

**Comment by jfy133** [comment]
It's coming in the next reelase :tada:

**Comment by flashton2003** [comment]
When's that scheduled for, approximately?

**Comment by jfy133** [comment]
I'm going to say two months (realistically) as I have to teach a summer school next month and we are entering holiday periods, but we will see if we can do it a bit faster :)

**Comment by jfy133** [comment]
Ref: https://github.com/nf-core/taxprofiler/milestone/2

**Comment by flashton2003** [comment]
Thanks James.
