### ISSUE TITLE
unable to read taxprofiler.nf file

### ISSUE THREAD

**Issue by wanghy73** [nf-core/taxprofiler#277]
### Description of the bug

why I got the following error?
/root/.nextflow/assets/nf-core/taxprofiler/./workflows/taxprofiler.nf' -- cause: /home/nextflow/samplesheet.csv

here is the location
ls -l /root/.nextflow/assets/nf-core/taxprofiler/workflows/taxprofiler.nf
-rw-r--r--. 1 root root 15573 Apr  2 09:09 /root/.nextflow/assets/nf-core/taxprofiler/workflows/taxprofiler.nf

how can I remove those extra . in the path

### Command used and terminal output

```console
./nextflow run nf-core/taxprofiler --input samplesheet.csv --databases database.csv --outdir  /mnt/mmce-efs/tax-results/ --run_kraken2 --run_krakenuniq -profile docker
```

### Relevant files

 https://github.com/nf-core/taxprofiler/blob/master/CITATIONS.md
-^[[2m----------------------------------------------------^[[0m-
Apr-02 09:10:32.534 [main] ERROR nextflow.cli.Launcher - Unable to read script: '/root/.nextflow/assets/nf-core/taxprofiler/./workflows/taxprofiler.nf' -- cause: /home/nextflow/samplesheet.csv

### System information

N E X T F L O W  ~  version 22.10.7

**Comment by jfy133** [comment]
Hi @wanghy73 

I am able to run the pipeline myself with your command. Please could you share the `.nextflow.log` file that is generated wherever you ran the command.

The issue is not the `.` but rather the `samplesheet.csv`

```
cause: /home/nextflow/samplesheet.csv
```

Could you share this file with me? If privately, you can [email](mailto:jfy133@gmail.com) me the file

**Comment by wanghy73** [comment]
I see. I don't have this file /home/nextflow/samplesheet.csv. where this file could locate?

**Comment by jfy133** [comment]
This is a user error, supporting now via email
