### ISSUE TITLE
Compatibility with nf-core/fetchngs

### ISSUE THREAD

**Issue by artur-matysik** [nf-core/taxprofiler#281]
### Description of feature

Taxprofiler uses custom sample sheet CSV as an input. 
It will be great if it can also digest `samplesheet.csv` generated by [nf-core/fetchngs](https://github.com/nf-core/fetchngs), that needs only small reshaping and column name change. 
Or maybe it does already?

**Comment by jfy133** [comment]
Hi @artur-matysik !

Already supported 😎 (well should do anyway 👀)

See this fetchngs parameter: https://nf-co.re/fetchngs/1.9/parameters#nf_core_pipeline and the drop down!
