### ISSUE TITLE
TAXPASTA_MERGE failing if only one sample provided. Add warning or single sample handling. 

### ISSUE THREAD

**Issue by artur-matysik** [nf-core/taxprofiler#282]
### Description of feature

I was trying to run the pipeline for testing reasons on single sample and kept getting the below error. 
Took me a while to realize that (most likely) reason behind that was providing only one sample - with two or more it was all fine. 
Not reporting as a bug, but it will be nice to be able to process single sample as well (or at least drop some warning message). 

```
Error executing process > 'NFCORE_TAXPROFILER:TAXPROFILER:STANDARDISATION_PROFILES:TAXPASTA_MERGE (db5)'

Caused by:
  Essential container in task exited

Command executed:

  taxpasta merge \
      -p kaiju -o kaiju_db5.tsv \
       \
       \
      DRX120220_pe_DRR127476_db5.kaijutable.txt


  cat <<-END_VERSIONS > versions.yml
  "NFCORE_TAXPROFILER:TAXPROFILER:STANDARDISATION_PROFILES:TAXPASTA_MERGE":
      taxpasta: $(taxpasta --version)
  END_VERSIONS

Command exit status:
  2

Command output:
  [04:35:45] CRITICAL Only a single profile was provided. Please      merge.py:404
                      provide at least two.

Command error:
  [04:35:45] CRITICAL Only a single profile was provided. Please      merge.py:404
                      provide at least two.
```

**Comment by jfy133** [comment]
Good point.

@Midnighter should we just filter out or just sent single samples to `taxpasta standardise` instead?

**Comment by Midnighter** [comment]
I suppose, standardising a single profile would be most in line with user intention when they request to run taxpasta?

**Comment by jfy133** [comment]
OK, will try and work out a system there.
