### ISSUE TITLE
Improved documentation for running mOTUs

### ISSUE THREAD

**Issue by alneberg** [nf-core/taxprofiler#283]
### Description of feature

The description "is composed of code and database together." is a bit non-informative. I think referring to the `motus downloadDB` command would be better?

Also, I expected the links to the tools to lead to the tools themselves and not documentation on how to build custom databases, but not sure how to solve that.

**Comment by jfy133** [comment]
Fixed the mOTUs issue, the second I'm not sure needs a change - we have a sentence right below that says to click to the section using the links (however I've added more emphasise to make it eye-catch worthy)

**Comment by alneberg** [comment]
Excellent, thank you!
