### ISSUE TITLE
Increase memory for falco in config

### ISSUE THREAD

**Issue by sofstam** [nf-core/taxprofiler#291]
### Description of feature

[Falco module](
 https://github.com/nf-core/taxprofiler/blob/master/modules/nf-core/falco/main.nf) has `process_small` as label. 
 The error `malloc(): unsorted double linked list corrupted` has been reported in some samples. We need to bump falco in taxprofiler's config.

**Comment by LilyAnderssonLee** [comment]
Should I set the maximum memory to 36GB?

**Comment by sofstam** [comment]
yes!
