### ISSUE TITLE
Validation fail with multiple ranks passed to --kaiju_taxon_rank

### ISSUE THREAD

**Issue by artur-matysik** [nf-core/taxprofiler#295]
### Description of the bug

From documentation, multiple ranks can be passed to `--kaiju_taxon_rank`. 

>Specify the taxonomic level(s) to be displayed in the resulting Kaiju taxon table, as generated by the kaiju2table helper tool.
This can be either a single level (e.g. species), or a comma separated list to display the full taxonomic path (e.g. `superkingdom,phylum,class,order,family,genus,species`.).

While trying to use e.g.: 
`--kaiju_taxon_rank 'genus,species'`

I get: 

```
ERROR: Validation of pipeline parameters failed!
* --kaiju_taxon_rank: 'genus,species' is not a valid choice (Available choices (5 of 6): phylum, class, order, family, genus, ... )
```

Is it a bug or am I just doing something wrong here? 
Thanks!

### Command used and terminal output

```console
# Netflow run
nextflow run taxprofiler \
-profile docker,test \
--kaiju_taxon_rank 'genus,species'

# Error message
ERROR: Validation of pipeline parameters failed!
* --kaiju_taxon_rank: 'genus,species' is not a valid choice (Available choices (5 of 6): phylum, class, order, family, genus, ... )
```

### System information

Nextflow version: 22.10.7
Hardware: Desktop
Executor: Local
Container engine: Docker
OS: Ubuntu
Version of nf-core/taxprofiler: v1.0.0

**Comment by jfy133** [comment]
@Midnighter can you cross check the pipeline parameters with taxpasta itself? (Note the older version still in the pipeline though)

**Comment by artur-matysik** [comment]
I tried to lift the input restriction in nextflow schema (`nf-core schema build`), and it was working for Kaiju, but then I'm getting error with `kaiju2table`:

```
Caused by:
  Process `NFCORE_TAXPROFILER:TAXPROFILER:PROFILING:KAIJU_KAIJU2TABLE_SINGLE (ERX5474932_pe)` terminated with an error exit status (1)

Command executed:

  dbnodes=`find -L kaiju_test -name "*nodes.dmp"`
  dbname=`find -L kaiju_test -name "*.fmi" -not -name "._*"`
  kaiju2table    \
      -t $dbnodes \
      -n $dbname \
      -r genus,species \
      -o ERX5474932_pe_ERR5766176_kj_test.kaijutable.txt \
      ERX5474932_pe_ERR5766176_kj_test.kaiju.tsv
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_TAXPROFILER:TAXPROFILER:PROFILING:KAIJU_KAIJU2TABLE_SINGLE":
      kaiju: $(echo $( kaiju -h 2>&1 | sed -n 1p | sed 's/^.*Kaiju //' ))
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Error: Rank must be one of: phylum, class, order, family, genus, species.
```

From [Kaiju documentation](https://github.com/bioinformatics-centre/kaiju) it looks like that only single rank can be provided with `-r`, therefore error I guess. 

As a word of explanation, what I was aiming to do overall, was to end up with Kaiju profile for different ranks - similar like in Kraken2 report. 
Of course I can 'recover' higher ranks from the lineage, but in my understanding it is not the same thing. 
E.g. having two different species with the same root genus1 with respective counts:
genus1 (100) > species1 (not assigned)
genus1 (100) > species2 (100) 
Total genus1 counts = 200, while species2 = 100 (species1 was not assigned). When estimating higher ranks based on species level count for genus1 will be underestimated (100). Or is my understanding here completely wrong? 
I am sorry if that is off topic (feel free to remove comment), just wanted to understand and apply pipeline (and individual tools) functionality here :)

**Comment by Midnighter** [comment]
@jfy133 this is not taxpasta related.

**Comment by jfy133** [comment]
Whoops, completely misread the intro :facepalm:, I keep forgetting about the 'native' table stuff - sorry both! 

Indeed, it looks like this is a mis-documented parameter. I will make PR for the next release in hte next couple of days.
