### ISSUE TITLE
Profiler request: kaiju

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#3]
### Description of feature

Kaiju is a program for sensitive taxonomic classification of high-throughput sequencing reads from metagenomic whole genome sequencing or metatranscriptomics experiments

https://kaiju.binf.ku.dk/

**Comment by talnor** [comment]
Tasks:
- [x] Add kaiju command to nf-core modules
- [ ] Add kaiju2table command to nf-core modules
- [ ] Include modules in taxprofiler

**Comment by sofstam** [comment]
I am closing this issue #67
