### ISSUE TITLE
Add functionality to turn read QC on/off

### ISSUE THREAD

**Issue by vinisalazar** [nf-core/taxprofiler#324]
### Description of feature

Hi,

Thank you for providing taxprofiler. It is a fantastic tool.

Sometimes I run the workflow and I don't want to have to run the FastQC/Falco step, either because I have already ran it before and am unable to get the `-resume` mechanism to pick it up, or I simply don't need it.

Would it be possible to add the functionality to turn it on/off, like with the adapter trimming step?

I have managed to deactivate it locally on my copy of the workflow. Would you welcome a PR attempting to add this functionality?

Thank you for any assistance you can provide.

Best,
Vini

**Comment by jfy133** [comment]
Your wish is my  command :point_up:!

**Comment by vinisalazar** [comment]
Thank you so much @jfy133 !
