### ISSUE TITLE
Use quickBAM 

### ISSUE THREAD

**Issue by sofstam** [nf-core/taxprofiler#344]
### Description of feature

https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btad463/7232227

**Comment by jfy133** [comment]
Doies that acutally make sense for teh pipeline? My understanding it's an API.library rather than CLI software... (right @Midnighter ?)
?

**Comment by Midnighter** [comment]
Yes, sorry. I posted it in the channel, 'cause I thought it'd be of interest to people that this exists. I don't see that we're able to use it directly ourselves but the tools that we use would have to switch to using quickBAM.
