### ISSUE TITLE
Add support for sequencing coverage esimates with nonpareil

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#384]
### Description of feature

Main module here: https://github.com/nf-core/modules/pull/3885

Might be nice to also make a MultiQC module for rendering curves.

Important: requires uncompressing FASTQ files for input! will need to give big warnings about disk space on this.

**Comment by jfy133** [comment]
Maybe should update the module to conditionally unzip within it, rather than expected it outside

**Comment by Midnighter** [comment]
I was thinking, it would be awesome to have a QC step that shows an overview of where classified reads map on the identified reference genomes. Can nonpareil generally do that or does it only deliver estimates on how much coverage was achieved?

**Comment by jfy133** [comment]
No, it purely aligns reads to themselves to check for redundancy essentially.

I'm not really sure there is a tool that does what you're asking for at a metagenomic level...

**Comment by jfy133** [comment]
Done in in the pr that GitHub mobile is not finding stm
