### ISSUE TITLE
Preprocessing: long read host removal

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#40]
### Description of feature
To remove e.g. human reads

### What needs to be done
Use minimap2 to remove human reads from nanopore reads. [Minimap2](https://github.com/nf-core/modules/tree/e20e57f90b6787ac9a010a980cf6ea98bd990046/modules/minimap2) is already implemented as nf-core module.

### This can be closed when
 - [ ] Minimap2 has been merged to dev branch.

**Comment by jfy133** [comment]
Sounds good to me!

**Comment by jfy133** [comment]
Make sure to make minimap2 index generation is optional, as with short-reads

**Comment by ljmesi** [comment]
Ok. I'll implement it in that way.
