### ISSUE TITLE
megan version 6.21.7 throw `java.lang.NullPointerException` error

### ISSUE THREAD

**Issue by MajoroMask** [nf-core/taxprofiler#407]
### Description of the bug

Hi guys it's me again, I been testing my local sets of taxprofiler reference and encountered this bug. 

- The test data is standard (sample "2612" ERX5474932_ERR5766176_*.fastq.gz and "2613" ERX5474937_ERR5766181_*.fastq.gz)
- All the database is from my local build.

The error massage kinda like this:

```log
Caused by:
  Process `NFCORE_MAG:MAG:VISUALIZATION_KRONA:MEGAN_RMA2INFO_KRONA (2613.phix_removed.unmapped_1 - virus-malt)` terminated with an error exit status (1)

Command executed:

  rma2info \
      -i 2613.phix_removed.unmapped_1.rma6 \
      -o 2613.phix_removed.unmapped_1_virus-malt.txt.gz \
       \
      --read2class Taxonomy
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MAG:MAG:VISUALIZATION_KRONA:MEGAN_RMA2INFO_KRONA":
      megan: $(echo $(rma2info 2>&1) | grep version | sed 's/.*version //g;s/, built.*//g')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Error: JavaFX detected no fonts! Please refer to release notes for proper font configuration
  Version   MEGAN Community Edition (version 6.21.7, built 23 Jun 2021)
  Author(s) Daniel H. Huson
  Copyright (C) 2021 Daniel H. Huson. This program comes with ABSOLUTELY NO WARRANTY.
  Loading ncbi.map: 2,302,807
  Loading ncbi.tre: 2,302,811
  Caught:
  java.lang.NullPointerException
  	at megan/megan.tools.RMA2Info.isDescendant(RMA2Info.java:455)
  	at megan/megan.tools.RMA2Info.reportRead2Count(RMA2Info.java:387)
  	at megan/megan.tools.RMA2Info.run(RMA2Info.java:153)
  	at megan/megan.tools.RMA2Info.main(RMA2Info.java:63)

Work dir:
  /path/df/00a947f63ff0bfab7feeb6ca32a317

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

I noticed that the megan has a newer version docker container in biocontainer project, so I tried to modify `modules/nf-core/megan/rma2info/main.nf` as below, and the problem got solved:

```diff
process MEGAN_RMA2INFO {
    tag "$meta.id"
    label 'process_single'

-     conda "bioconda::megan=6.21.7"
-     container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
-         'https://depot.galaxyproject.org/singularity/megan:6.21.7--h9ee0642_0':
-         'biocontainers/megan:6.21.7--h9ee0642_0' }"
+     conda "bioconda::megan=6.24.20"
+     container 'quay.io/biocontainers/megan:6.24.20--h9ee0642_0'

    input:
    tuple val(meta), path(rma6)
    val(megan_summary)
```

I'm just a engineer here in my facility so I did not look into it further. Do you guys need to check this out?

### Command used and terminal output

```console
nextflow run ./main.nf -profile test,docker --outdir test --run_krona true --krona_taxonomy_directory /local/path/krona/taxonomy.tab
```

**Comment by jfy133** [comment]
Hi @MajoroMask I can't replicate...

The only thing I can think of is you maybe hit a memory error (java is really wierd and inconsistent with memory usage)... , MALT/MEGAN databases are extremely large, so if you have a custom one that could cause errors.

Could you try increasing the amount of memory to that process with a config file, before we bump the version in a patch release (although this will come in the next major release)?

**Comment by MajoroMask** [comment]
Hi @jfy133 Thanks for your reply. 

I tried your solution and I think this time it's not the out of memory issue.

- The exit code is `1` instead of `137` or other that represent memory shortage.

```bash
cd /path/into/workdir/34/3e38ec40e5e77328f24cffaba38e1e
cat .exitcode
1
```

- I tried increase `task.memory` for this process to 50GB, yet still I got the same error.

```bash
cat .command.run | grep 'docker run * --memory'
docker run -i --cpus 1.0 --memory 51200m -e "NXF_DEBUG=${NXF_DEBUG:=0}"
```

- The error massage pointed out it's a classic java "null pointer" error. I'm not familiar with java so I'll leave it to your guys. 

```bash
cat .command.err
Error: JavaFX detected no fonts! Please refer to release notes for proper font configuration
Version   MEGAN Community Edition (version 6.21.7, built 23 Jun 2021)
Author(s) Daniel H. Huson
Copyright (C) 2021 Daniel H. Huson. This program comes with ABSOLUTELY NO WARRANTY.
Loading ncbi.map: 2,302,807
Loading ncbi.tre: 2,302,811
Caught:
java.lang.NullPointerException
        at megan/megan.tools.RMA2Info.isDescendant(RMA2Info.java:455)
        at megan/megan.tools.RMA2Info.reportRead2Count(RMA2Info.java:387)
        at megan/megan.tools.RMA2Info.run(RMA2Info.java:153)
        at megan/megan.tools.RMA2Info.main(RMA2Info.java:63)
```

- I also checked the release note of megan ([here](https://software-ab.cs.uni-tuebingen.de/download/megan6/release_notes.txt)) and I found this:

```txt
--- Release notes MEGAN6 V6_21_11 (Fri, 20 Aug 2021): ---

- Fixed newly introduce bug in Project menu
- Fixed minor bug in rma2info
```

Since megan is not open source, I think we can't confirm it on code level. The only thing we know is that they do have a `rma2info` bug fixed between release 6.21.7 and 6.24.20. So fixing this problem by updating megan version makes sense to me.

That's all I have for now. Hope this information could be of help for you guys.

**Comment by MajoroMask** [comment]
Well, turns out megan CE is open source ([the commit](https://github.com/husonlab/megan-ce/commit/1e2a788a0508ae038d0d08425546e77c84d768dc#diff-2dd2056b8cc3c639bb630001ac3f5ba2518026f66d345bf710ea80bae5c85b6a))

![image](https://github.com/nf-core/taxprofiler/assets/19700954/cdb97a05-abdd-4f9c-83de-59ca6872c028)

**Comment by jfy133** [comment]
OK! Thanks @MajoroMask that's enough to warrant the bump.

I will aim to update the module and pipeline over the next few days and include taht with the other bug fixes :)

**Comment by jfy133** [comment]
First step: module update https://github.com/nf-core/modules/pull/4228
