### ISSUE TITLE
Documentation: Broken Links in "Full database sheet" Section

### ISSUE THREAD

**Issue by lennijusten** [nf-core/taxprofiler#418]
## Description
I encountered an issue with the documentation on the "Full database sheet" section of the [TaxProfiler documentation (v1.1.2)](https://nf-co.re/taxprofiler/1.1.2/docs/usage). The links intended to guide users to tutorials for generating custom databases for various tools are not functioning correctly.

## Issue Details
The tool names in the list (e.g., Kraken2, KMCP, MetaPhlAn, Kaiju, Bracken, etc.) are hyperlinked to their respective tutorial pages. However, clicking on any of these links leads to a browser error stating: "This page isn’t working nf-co.re redirected you too many times. Try deleting your cookies. ERR_TOO_MANY_REDIRECTS".

I have attempted to resolve this by clearing cookies and using different browsers (Safari and Chrome), but the issue persists. This suggests to me that the problem is with the website or the link structure.

**Comment by jfy133** [comment]
@mashehu any suggestion? Could we have added the links 'badly' in the markdown or is it a website backend thing?

**Comment by jfy133** [comment]
I can confirm the behaviour happens on my end too, specifically this links at the bottom of this section:

https://nf-co.re/taxprofiler/1.1.2/docs/usage#full-database-sheet

**Comment by mashehu** [comment]
Fixed!

**Comment by jfy133** [comment]
Thanks!
