### ISSUE TITLE
Postprocessing: visualisation (Krona)

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#44]
### Description of feature

It would also be nice to include some nice visualisation output to help more rapidly visualse profiles outside of just tables.

@jianhong already has implemented something similar in a personal equiavlent of taxprofiler (https://github.com/jianhong/shotgun), so should be pretty easy to port over.

one common tool is [Krona](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-12-385) plots s would be nice to add

**Comment by jfy133** [comment]
Supported profliers:

- [ ] Kaiju (`kaiju2krona`)
- [ ] MALT/MEGAN (?) (but possibly not accessible from commandline...? Need to check rma2info to get the CSV format thing MEGAN and then import into krona with `ktImportTaxonomy`)

**Comment by MillironX** [comment]
In regards to Kraken2 support, you could instead use `kreport2krona` from https://github.com/jenniferlu717/KrakenTools. This is what I do in https://github.com/ksumngs/v-met/blob/v1.0.1/main.nf#L141-L146.

**Comment by MillironX** [comment]
I might suggest using https://github.com/khyox/recentrifuge, instead though. It's a souped-up version of Krona that supports

- Centrifuge
-  LMAT
- CLARK
- Kraken

out of the box without adding an extra conversion step, and can take any generic CSV/TSV as input, too. It includes confidence scores along with the taxonomy classifications. The downside is that it requires a NCBI taxonomy database to run. It could be downloaded on-the-fly using the included `retaxdump`, or could be a required input from the user.

**Comment by jfy133** [comment]
Thanks @MillironX ! Tha'ts really useful to know. I guess we will need to make another module for KrakenTools, but as it has Kraken/Bracken already that would be really helpful already.

For Recentrifuge, that does look interesting however, that any input appears to require some form of 'score' (from a quick skim of the docs) it might be a problem for may of the profilers.

That said, It could still be useful to have in the future as an alternative to Krona. Could you please make a separate issue requesting this tool? I would then assign it for a future release (rather than the first version, as I would need more time to investigate this).

**Comment by jfy133** [comment]
https://github.com/nf-core/modules/issues/1741

**Comment by jfy133** [comment]
Due to difficulties in converting some of the output files to Krona output (as they are not directly supported), and generally an opinion of 'it's pretty, but I don't really use it', We will leave the current status of Krona as it is with only some of the tools implemented. If anyone else wants to revisit this in the future, we would be happy to see this expanded - but for now this is sufficient.
