### ISSUE TITLE
Move/copy DB troubleshooting content from Usage/Tutorial to Usage/ or new Usage/Database-troubleshooting

### ISSUE THREAD

**Issue by vmkalbskopf** [nf-core/taxprofiler#456]
### Description of the bug

After running into a classic bug in the way mOTUS locates it's database, [I was pointed](https://nfcore.slack.com/archives/C031QH57DSS/p1710425899671209) to [the docs](https://nf-co.re/taxprofiler/1.1.5/docs/usage/tutorials#motus-custom-database) which described my exact issue. I had gone through the docs, but skipped the [Tutorial](https://nf-co.re/taxprofiler/1.1.5/docs/usage/tutorials) section (I suspect most devs skip the tutorial), and only read the [Usage](https://nf-co.re/taxprofiler/1.1.5/docs/usage) section. 

Perhaps the [database section](https://nf-co.re/taxprofiler/1.1.5/docs/usage/tutorials#retrieving-databases-or-building-custom-databases) could be copied or moved to the general [Usage](https://nf-co.re/taxprofiler/1.1.5/docs/usage) page. I think this would be a more obvious location for such vital information.

**Comment by jfy133** [comment]
Done in https://github.com/nf-core/taxprofiler/commit/b5081b04f821eb7b85eac9b45784349403def8fe!
