### ISSUE TITLE
Failed to produce kaiju_combined_reports.txt

### ISSUE THREAD

**Issue by LilyAnderssonLee** [nf-core/taxprofiler#460]
### Description of the bug

The process `STANDARDISATION_PROFILES:KAIJU_KAIJU2TABLE_COMBINED` was ignored due to the empty input files passed from the function `combineProfilesWithDatabase`
- ch_input_for_kaiju2tablecombine.profile
- ch_input_for_kaiju2tablecombine.db

```
ch_input_for_kaiju2tablecombine = combineProfilesWithDatabase(ch_profiles_for_kaiju, ch_input_databases.kaiju)

KAIJU_KAIJU2TABLE_COMBINED ( ch_input_for_kaiju2tablecombine.profile, ch_input_for_kaiju2tablecombine.db, params.kaiju_taxon_rank)

```

`ch_profiles_for_kaiju` channel:  

`[['tool':'kaiju', 'db_name':'db5', 'db_params':''], /home/lili.li/taxprofiler_kaiju/work/4c/cf5f35eb935c39f5a059b35a7d1a87/kaiju]`

ch_input_databases.kaiju channel: 

`[['id':'db5'], [/home/lili.li/taxprofiler_kaiju/work/36/5b9bdc42eeff80a83592e27072b2c1/2611_se_db5.kaiju.tsv, /home/lili.li/taxprofiler_kaiju/work/f4/458637db0c1a2a7a0b3535006cdd9b/2613_se_db5.kaiju.tsv, /home/lili.li/taxprofiler_kaiju/work/b4/4a80a452449621a7a05504f251bd64/ERR3201952_se_db5.kaiju.tsv, /home/lili.li/taxprofiler_kaiju/work/c2/a8857244f71dc5db7ddce84adf32c4/2612_se_db5.kaiju.tsv]]`

### Command used and terminal output

```console
nextflow run nf-core/taxprofiler r 1.1.5 -profile singularity,test --outdir results
```

**Comment by LilyAnderssonLee** [comment]
@Midnighter, you might have a better understanding of this function. Could you please take a look at these issues?

**Comment by Midnighter** [comment]
Do you have logs from the Kaiju step itself? Empty files are usually produced when nothing was detected.

**Comment by LilyAnderssonLee** [comment]
Do you mean log files from the process `KAIJU_KAIJU`? They are actually empty. Or are you referring to log files from a different process?

I don't think this issue was caused by the empty files, as I am not receiving the combined report in my clinical samples either.

**Comment by LilyAnderssonLee** [comment]
Fixed in https://github.com/nf-core/taxprofiler/pull/464.
