### ISSUE TITLE
taxprofiler krona output files missing

### ISSUE THREAD

**Issue by aslangabriel99** [nf-core/taxprofiler#479]
### Description of the bug

I  ran the pipeline with the command "nextflow run nf-core/taxprofiler -r 1.1.0 -profile docker \
--input samplesheet_06YRkraken.csv --databases database_06YRkraken.csv --outdir ./06YRkrakenkaijuresults \
--perform_shortread_qc \
--perform_shortread_hostremoval --hostremoval_reference OR666647_1_DHAV3.fna \
--perform_runmerging --save_runmerged_reads \
--run_kraken2 --run_kaiju \
--run_profile_standardisation \
--max_cpus 11 --max_memory '125.GB" , following the turotial. But there are no krona output files found.

**Comment by jfy133** [comment]
Hi @aslangabriel99 

Unless I'm missing something, you didn't supply `--run_krona`.

Please check the parameter documentation here: https://nf-co.re/taxprofiler/1.1.6/parameters#run_krona

Closing now, but feel free to re-open if I did indeed miss something
