### ISSUE TITLE
All tools should have some form of MultiQC modules

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#48]
### Description of feature

If possible...

Currently supported by MultiQC

This can be closed when:

- [x] FASTQC
- [x] ADAPTERREMOVAL
- [x] FASTP
- [x] BBDUK (I think) [Possible] [@jfy133 - ewels/MultiQC/pull/1742]
- [x] PRINSEQPLUSPLUS [Possible] [@jfy133 ewels/MultiQC/pull/1741]
- [x] BOWTIE2
- [x] PORECHOP [Possible] [@jfy133 ewels/MultiQC/pull/1728]
- [x] Filtlong [Possible] [@sofstam ewels/MultiQC/pull/1732]
- [x] MALT
- [x] KRAKEN2
- [x] METAPHLAN3 [Possible via BowTie2 output, not particularly usefu ❌ not possible, just input reads and read length - not useful for QC here]
- [x] CENTRIFUGE apparently same/similar structure to Kraken [Both files do not have summary statistics, easiest might be BT2/HS2 copy)] -> Add custom file suffixes for kraken/centrifuge, use regex to separate the two modules and update title [@jfy133 nf-core/taxprofiler/pull/109]
- [x] KAIJU - MultiQC parses the output generated by `kaiju2table` from [Kaiju](http://kaiju.binf.ku.dk/). Module implementation for `kaiju2table` is required.
- [x] DIAMOND [Possible] [@mjamy ewels/MultiQC/pull/1731]
- [x] mOTUs [Possible - https://github.com/ewels/MultiQC/pull/1747]
- [ ] PORECHOP_ABI
- [x] FALCO (?) - it seems that it is supported by FASTQC

**Comment by sofstam** [comment]
Centrifuge and porechop are not supported by multiqc at the moment.

**Comment by jfy133** [comment]
Yup exactly, this is why they are not yet ticked :)

**Comment by jfy133** [comment]
Ok BBDuk not displayed as our particular command isn't supported by MQC (as in the requested search patterns not found)

https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml

**Comment by jfy133** [comment]
Note issue: https://github.com/nf-core/taxprofiler/issues/38#issuecomment-1107407709

**Comment by jfy133** [comment]
Current issues:

- [ ] [2022-05-10 10:11:54,296] multiqc.modules.malt.malt                          [DEBUG  ]  Duplicate sample name found! Overwriting: 2612_ERR5766180.unmapped (I guess based on name stored in log, need to infer from directory name -  so need to stage in MQC report work dir  directory?)?
- [ ] [2022-05-10 10:11:54,285] multiqc.modules.base_module                        [DEBUG  ]  bowtie2 - Skipping './2612_ERR5766176_B.bowtie2.log' as it didn't match the path_filters for 'Bowtie 2 / HiSAT2' (dafuq?)

**Comment by jfy133** [comment]
Fix for centrifuge/kraken in!

**Comment by jfy133** [comment]
Just waiting for the final modules for MQC then we can merge

**Comment by sofstam** [comment]
I think we have forgotten minimap2 for long-reads.
