### ISSUE TITLE
Recommended procedure for profiling nanopore data

### ISSUE THREAD

**Issue by bcpd** [nf-core/taxprofiler#480]
### Description of feature

Could you recommend what the current best practices around taxonomic profiling of nanopore data (r10.4.1) are? Many thanks - and thank you for developing this tool.

**Comment by jfy133** [comment]
Hi @bcpd 

Within taxprofiler there isn't currently any particular guidance other than make sure your database parameters are adapted for long reads.

I would recommend checking the literature for specific advice on which tools would be most suitable for your particular project and compare with what is available in the pipeline.

Note that our next major release (1.2) will extend to more long-read specific profilers.
