### ISSUE TITLE
Add separate workflow for database building

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#49]
### Description of feature

I guess it could maybe be nice to have a entirely separate workflow

e.g. 

```console
nextflow run nf-core/taxprofiler --taxprofiling
```

vs

```console
nextflow run nf-core/taxprofiler --dbbuilding
```

or something, where the latter could somehow allow you to build from the same set of input FASTA files databases with all our supported tools?

I don't know if this would be of interest given all tools would likely need a lot of tuned parameters? But maybe that's OK if we supply with an another TSV sheet or something...

**Comment by Midnighter** [comment]
I don't know if it should be part of taxprofiler or external workflows. Building databases is probably useful for multiple pipelines. Or we just go with the one sub-workflow per database approach.

**Comment by jfy133** [comment]
After various discussions we decided to go for it, and as a separate workflow within the pipeline (with reuseable subworkflows on the new nf-core shareable subworkflow ).

This will be useful for taxpasta and the possible consensus caller as it will ensure you have the same set of genomes for each profiler

**Comment by Midnighter** [comment]
Just to collect:

* mOTUs https://github.com/motu-tool/mOTUs/issues/47
* sourmash https://github.com/UnseenBio/build-sourmash-index
* kraken2/Bracken https://github.com/Midnighter/kraken2-bracken-test-db

plus we have the commands used for generating the test databases https://github.com/nf-core/test-datasets/blob/taxprofiler/README.md

**Comment by jfy133** [comment]
Also here: https://nf-co.re/taxprofiler/dev/usage#retrieving-databases-or-building-custom-databases

**Comment by jfy133** [comment]
Possible 'preprocessing' steps:

1. Nr. of genome reduction by similarity clustering + representative selection (possible tools [dRep](https://drep.readthedocs.io/en/latest/overview.html), [Galah](https://github.com/wwood/galah))
2. Genome masking(?)

Both with the aim of reducing database size 

Note all would be optional _and_ opt in as they can have quite significant effects if not used correctly

**Comment by jfy133** [comment]
Ended up going with a separte pipeline 

https://github.com/nf-core/createtaxdb
