### ISSUE TITLE
Update nonpareil to allow gzip input

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#502]
### Description of feature

As this support has been added over the weekend

**Comment by Thomieh73** [comment]
hey @jfy133 I was wondering, how can I use the nonpareil tool with taxprofiler? is that option available in the last public release, 1.1.8?
I would very much like to use it in this workflow, when possible. Otherwise, I run it on the side.

**Comment by jfy133** [comment]
Hi @Thomieh73

Nonpareil  it is already is in our upcoming major release.

However note this version of nonpareil in that branch is the one without gzip support.

If you are happy to run with bleeding edge, you can try it by setting the pipeline version with `-r bouncy-basenji`.

Otherwise for now I recommend running it separately

**Comment by Thomieh73** [comment]
Hi @jfy133 thanks for the quick response. Okay, I will try it out with using the version from bouncy-basenji, and see how that works. :-)

**Comment by LilyAnderssonLee** [comment]
Fixed in #515
