### ISSUE TITLE
Can't pass `save_analysis_ready_fastqs` in local configuration file. 

### ISSUE THREAD

**Issue by muniheart** [nf-core/taxprofiler#520]
### Description of the bug

I want to run workflow with `params.save_analysis_ready_fastqs = true`.  When I pass this in local configuration file, [my.zip](https://github.com/user-attachments/files/16913184/my.zip), my.config, the parameter does not take effect, but when I pass it on the command-line or in a param-file, my.json, it does take effect.  Is there some issue with the manner in which configuration file 'conf/modules.config' is included from 'nextflow.config'?

### Command used and terminal output

```console
Pass parameter in local configuration file ``my.config``. Run workflow with command,

nextflow -log $OUTDIR/nextflow.log -c my.config \
    run nf-core/taxprofiler \
    -w $WORKDIR --outdir $OUTDIR -dump-hashes json \
    -profile singularity \
    --input                             input/samplesheet.csv \
    --databases                         databases.csv \
    --perform_shortread_qc              true \
    --shortread_complexityfilter_tool   fastp
```
directory `results/analysis_ready_fastqs` is not created.  When I pass the parameter on command-line,
```
nextflow -log $OUTDIR/nextflow.log \
    run nf-core/taxprofiler \
    -w $WORKDIR --outdir $OUTDIR -dump-hashes json \
    -profile singularity \
    --input                             input/samplesheet.csv \
    --databases                         databases.csv \
    --perform_shortread_qc              true \
    --shortread_complexityfilter_tool   fastp \
    --save_analysis_ready_fastqs        true
```
directory `results/analysis_ready_fastqs` is created, and it contains the processed fastqs.

The directory with processed fastqs is created when I pass the parameter in a params-file, too,
```
nextflow -log $OUTDIR/nextflow.log \
    run nf-core/taxprofiler -revision $REVISION \
    -params-file my.json \
    -w $WORKDIR --outdir $OUTDIR -dump-hashes json \
    -process.executor local \
    -profile singularity \
    --input                             input/samplesheet.csv \
    --databases                         databases.csv \
    --perform_shortread_qc              true \
    --shortread_complexityfilter_tool   fastp
```
```


### Relevant files

[my.zip](https://github.com/user-attachments/files/16913191/my.zip)


### System information

_No response_

**Comment by muniheart** [comment]
N E X T F L O W  ~  version 23.10.0
hardware: HPC
executor: tested on `local` and `slurm`
container: apptainer
OS version: AlmaLinux 9.3
version of nf-core/taxprofiler: 1.1.8

**Comment by muniheart** [comment]
From file, taxprofiler/docs/usage.md,

:::warning Do not use -c <file> to specify parameters as this will result in errors. Custom config files specified with -c must only be used for [tuning process resource specifications](https://nf-co.re/docs/usage/configuration#tuning-workflow-resources), other infrastructural tweaks (such as output directories), or module arguments (args). :::

Not a bug, since it is clearly documented.

**Comment by jfy133** [comment]
Oops sorry I forgot to reply to this yesterday, but glad you 'solved' it!
