### ISSUE TITLE
KrakenUniq SE overwrites the output when there is an early dot in the sample name 

### ISSUE THREAD

**Issue by SannaAb** [nf-core/taxprofiler#533]
### Description of the bug

Hi, 

I noticed that krakenuniq overwrites the outputs for SE samples if you have a dot in the sample name. This is not an issue for PE samples. I will attach the command.sh for both SE and PE. 

Thank you so much for the help :)  

### Relevant files

[commands.zip](https://github.com/user-attachments/files/17132463/commands.zip)

### System information

version 1.1.8

**Comment by jfy133** [comment]
Eek! Good eyes @SannaAb ! Will try to address ASAP

**Comment by jfy133** [comment]
@SannaAb can you supply an aexample samplesheet where this happens?

**Comment by jfy133** [comment]
OK I think I've replciated it by duplicating the 2612 SE in `test.config` and updating all the sample names int eh samplesheet to add `.` everywhere, iself note:

- SE: /home/james/git/nf-core/taxprofiler/testing/work/fd/0dba3332867f2812521cf088e1d237 -> single output file 2612 (but two inputs)
- PE: /home/james/git/nf-core/taxprofiler/testing/work/f2/22df431515fbef1f5f202b272eade6 -> multiple for 2612/2613 (multiple inputs)

**Comment by SannaAb** [comment]
[SampleSheeet_Taxprofiler.csv](https://github.com/user-attachments/files/17145744/SampleSheeet_Taxprofiler.csv)

So fast! :D Thanks, if you still need an example sheet this should work.

**Comment by jfy133** [comment]
Basically this:

```
        strip_suffix() {
            local result=\$1
            # Strip any file extensions.
            echo "${result%%.*}"
        }
```

In the 'single end' condition of the PRELOADED_KRAKENUNIQ module is too aggressive beause `%%` is 'anything' whereas if we used just the single bash expansion operation of `%.*` it would only to the very last `.`.

However, this is problematic when we have `.fastq.gz` or `.fastq` files.

So need to find a way to account for both contexts.

**Comment by jfy133** [comment]
I've ran out of time and I'm away from this afternoon until Monday.

If @Midnighter happens to have time (as he wrote this module), maybe he can fix it in the meantime.

**Comment by jfy133** [comment]
```
            if [[ \$result =~ ".gz^"]]; then
                resulttmp=\${result%.gz}
                result="\${resulttmp%.*}"
            else;
                echo "\${result%.*}"
            fi
```

OI was trying this but it didn't work

**Comment by sofstam** [comment]
What was it that it did not work? That the `unmapped` was not in the filename?

![Image](https://github.com/user-attachments/assets/a98ab136-71e4-4c37-b728-7a7696e0b000)
