### ISSUE TITLE
Add nf-test to the pipeline

### ISSUE THREAD

**Issue by LilyAnderssonLee** [nf-core/taxprofiler#555]
### Description of feature

Add nf-test to the pipeline:
- add nf-test for each test config
- add nf-test for  each local subworkflow
- add nf-test for each local module

Refer to the suggestion from @LouisLeNezet  https://github.com/nf-core/taxprofiler/pull/554#pullrequestreview-2458817455

**Comment by jfy133** [comment]
I think we already have a very old issue on this from me 😅

**Comment by LilyAnderssonLee** [comment]
Aha ok then should I close this issue?

**Comment by LilyAnderssonLee** [comment]
Closed it. This issue was created https://github.com/nf-core/taxprofiler/issues/92
