### ISSUE TITLE
All reads from host-removal are published by default

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#57]
### Description of the bug

We are going with a more opt-in approach in the pipeline's preprocessing steps, and we should make sure that both align/unaligned are independently optionally published.

Also reference index files

**Comment by Midnighter** [comment]
I definitely agree with making mapped/unmapped reads available. However, isn't the host reference a necessary input? In that case I don't see why one would want it as an output.

**Comment by jfy133** [comment]
By reference, I mean the `.bt2` files generated by `bowtie2-build` not the fasta itself.

For versioning consistency, people may want to generate the index (.bt2) files the first time they run the pipeline, and then reuse those for future runs - thus the option to save these)
