### ISSUE TITLE
Add nonpariel

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#68]
### Description of feature

For complexity filtering

**Comment by jfy133** [comment]
I can't get this tool to run on any of the small test-data, which would suggest to be a possible high-failure rate in the pipeline... 

I will try with some larger data but I don't have high hopes here unfortunately, particularly given it also only accepts decompressed FASTQ files...

**Comment by jfy133** [comment]
Ended up deciding not to add this, see:

https://github.com/nf-core/modules/issues/1593#issuecomment-1114215861

Someone else is welcome to pick this up again if they find a solution

**Comment by jfy133** [comment]
To be clear: I'm not sure that was actually the issue

Apparnetly OpenMPI only works with alingment mode, and it was also the `kmer` method that was also taking >4-5 hours (and I cancelled it afer that)

**Comment by rpetit3** [comment]
How long do runs usually take?

**Comment by jfy133** [comment]
I don't know, I got frustrated after 4-5 hours
