### ISSUE TITLE
Read quality filtering for Nanopore data

### ISSUE THREAD

**Issue by sofstam** [nf-core/taxprofiler#69]
### Description of feature
We need to add an optional complexity filtering step for Nanopore data.

### What needs to be done:
- Investigate the available tools for Nanopore and implement/add it to nf-core/taxprofiler. https://github.com/B-UMMI/long-read-catalog.
- [Filtlong](https://github.com/nf-core/modules/tree/master/modules/filtlong) is already implemented as a module.

### This can be closed when:
 - [ ] One of the tools (filtlong/nanofilt) has been merged to nf-core/taxprofiler

**Comment by jfy133** [comment]
I would just add `nanofilt` to begin, and we can add the other if you prefer it downstream

**Comment by sofstam** [comment]
Sounds great!
