### ISSUE TITLE
Preprocessing: adapter clipping and merging

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#7]
### Description of feature

This could be done with e.g.

`fastp` or `adapterremoval`. We should find out what tools potential users would prefer.

**Comment by jfy133** [comment]
One question is paired-end input

| Tool | Supports PR input |
|-------|--------------------------|
| Kraken2 | T |
| MetaPhlAn3 | T |
| MALT | F |
| DIAMOND | |
| Centrifuge | |
| Kaiju | |
| mOTUs | |

**Comment by jfy133** [comment]
Ok by default will NOT merge (can be turned on), and provide a warning for tools that don't support that R1/R2 will be profiled separately

**Comment by Midnighter** [comment]
As yet another alternative, there is https://github.com/usadellab/Trimmomatic

**Comment by jfy133** [comment]
@Midnighter I'm going to close this now as it's covered the ones I originally described. I'll make a new issue for Trimmomatic
