### ISSUE TITLE
Profiler: MetaMaps 

### ISSUE THREAD

**Issue by sofstam** [nf-core/taxprofiler#70]
### Description of feature

MetaMaps is tool specifically developed for the analysis of long-read (PacBio/Oxford Nanopore) metagenomic datasets. It simultaenously carries out read assignment and sample composition estimation.It is faster than classical exact alignment-based approaches, and its output is more information-rich than that of kmer-spectra-based methods. For example, each MetaMaps alignment comes with an approximate alignment location, an estimated alignment identity and a mapping quality.
The approximate mapping algorithm employed by MetaMaps is based on [MashMap](https://github.com/marbl/MashMap). MetaMaps adds a mapping quality model and EM-based estimation of sample composition.

https://www.nature.com/articles/s41467-019-10934-2

Work in progress in nf-core/modules:
[MetaMaps](https://github.com/nf-core/modules/issues/1403)

**Comment by jfy133** [comment]
Waiting for a bug fix from the developer, will bump to next release

**Comment by jfy133** [comment]
There were still lots of problems on this despite a huge amount of work from @sofstam so I think this will not be worth it for the time being unless there are some updates to the tool
