### ISSUE TITLE
Find full-test data

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#85]
### Description of feature

These should be 3-5 'real life' samples that you would profile against.

Ideally these would be shortread/long read pairs.

**Comment by sofstam** [comment]
@jfy133 I got a response from our site that we cannot use any of our data as test data right now, we need an ethical approval that we will be working on during fall.

**Comment by jfy133** [comment]
OK lets just look for already published stuff :+1: 

Maybe: https://www.nature.com/articles/s41597-019-0287-z ?

**Comment by sofstam** [comment]
I will have a look at this!

**Comment by Midnighter** [comment]
Beyond the mock communities, I'm personally interested in using the CAMI data.

**Comment by jfy133** [comment]
And also need to decide databases, and where to store them (presumably aws...?)

**Comment by Midnighter** [comment]
I think Zenodo could be a good place if we want to publish the benchmark. Then every database has a DOI.

**Comment by jfy133** [comment]
I fear the file sizes for some will be too large for Zenodo (50GB limit) but we can see

**Comment by sofstam** [comment]
Minimum criteria for full-test data:

- Fastq files, 5 Illumina, 2 Nanopore
- Sequencing depth > 10M
- Shotgun experiment
- Multiple run accessions for one sample
- Host removal (contaminant preferably)

**Comment by sofstam** [comment]
https://www.nature.com/articles/s41597-019-0287-z 

I post the article here so we do not forget.

**Comment by jfy133** [comment]
Meslier2022 is what we are going for: https://www.nature.com/articles/s41597-022-01762-z

I did a test run:

```
nextflow run nf-core/taxprofiler
		 -profile mpcdf,raven
		 -r combine-kreports-fix
		 --input fulltest_samplesheet.csv
		 --databases fulltest_dbsheet.csv
		 --outdir ./results
		 --save_preprocessed_reads
		 --perform_shortread_qc
		 --shortread_qc_mergepairs
		 --perform_shortread_complexityfilter
		 --save_complexityfiltered_reads
		 --perform_longread_qc
		 --perform_shortread_hostremoval
		 --perform_longread_hostremoval
		 --hostremoval_reference 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/819/615/GCA_000819615.1_ViralProj14015/GCA_000819615.1_ViralProj14015_genomic.fna.gz'
		 --save_hostremoval_index
		 --save_hostremoval_mapped
		 --save_hostremoval_unmapped
		 --perform_runmerging
		 --save_runmerged_reads
		 --run_centrifuge
		 --centrifuge_save_reads
		 --run_diamond
		 --run_kaiju
		 --run_kraken2
		 --kraken2_save_reads
		 --kraken2_save_readclassification
		 --kraken2_save_minimizers
		 --run_krakenuniq
		 --krakenuniq_save_reads
		 --krakenuniq_save_readclassifications
		 --run_bracken
		 --run_malt
		 --malt_save_reads
		 --malt_generate_megansummary
		 --run_metaphlan3
		 --run_motus
		 --run_profile_standardisation
		 --run_krona
		 -ansi-log false
		 -with-tower
		 -resume
		 --run_metaphlan3
		 --run_motus
```

With a the following samplesheet:

```
sample,run_accession,instrument_platform,fastq_1,fastq_2,fasta
MOCK_001_Minion_R9,1,OXFORD_NANOPORE,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR976/000/ERR9765780/ERR9765780.fastq.gz,,
MOCK_002_Minion_R9,1,OXFORD_NANOPORE,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR976/001/ERR9765781/ERR9765781.fastq.gz,,
MOCK_003_Minion_R9,1,OXFORD_NANOPORE,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR976/002/ERR9765782/ERR9765782.fastq.gz,,
MOCK_001_Illumina_Hiseq_3000,1,ILLUMINA,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR976/006/ERR9765746/ERR9765746_1.fastq.gz,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR976/006/ERR9765746/ERR9765746_2.fastq.gz,
MOCK_002_Illumina_Hiseq_3000,1,ILLUMINA,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR976/007/ERR9765747/ERR9765747_1.fastq.gz,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR976/007/ERR9765747/ERR9765747_2.fastq.gz,
MOCK_003_Illumina_Hiseq_3000,1,ILLUMINA,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR976/008/ERR9765748/ERR9765748_1.fastq.gz,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR976/008/ERR9765748/ERR9765748_2.fastq.gz,
MOCK_003_Illumina_Hiseq_3000,2,ILLUMINA,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR976/009/ERR9765749/ERR9765749_1.fastq.gz,ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR976/009/ERR9765749/ERR9765749_2.fastq.gz,
```

And database sheet

```
tool,db_name,db_params,db_path
bracken,bracken-db,,/raven/ptmp/jfellowsy/databases/taxprofiler_full_test/meslier2022_final_dbs/tars/bracken.tar.gz
centrifuge,centrifuge-db,,/raven/ptmp/jfellowsy/databases/taxprofiler_full_test/meslier2022_final_dbs/tars/centrifuge.tar.gz
diamond,diamond-db,,/raven/ptmp/jfellowsy/databases/taxprofiler_full_test/meslier2022/diamond/diamond.dmnd
kaiju,kaiju-db,,/raven/ptmp/jfellowsy/databases/taxprofiler_full_test/meslier2022_final_dbs/tars/kaiju.tar.gz
kraken2,kraken2-db,,/raven/ptmp/jfellowsy/databases/taxprofiler_full_test/meslier2022_final_dbs/tars/kraken2.tar.gz
krakenuniq,krakenuniq-db,,/raven/ptmp/jfellowsy/databases/taxprofiler_full_test/meslier2022_final_dbs/tars/krakenuniq.tar.gz
malt,malt-db,,/raven/ptmp/jfellowsy/databases/taxprofiler_full_test/meslier2022_final_dbs/tars/malt.tar.gz
metaphlan3,metaphlan3-db,,/raven/ptmp/jfellowsy/databases/taxprofiler_full_test/meslier2022_final_dbs/tars/metaphlan3.tar.gz
motus,motus-db,,/raven/ptmp/jfellowsy/databases/taxprofiler_full_test/meslier2022_final_dbs/tars/motus.tar.gz
```

The databases TARs basd on these [instructions](https://hackmd.io/@jfy133/HJ3Pa4Mdo)

And it mostly ran! Observations in next commetn

**Comment by jfy133** [comment]
- [ ]  The multiQC report looks weird in a few places though
    - [ ] The nanopore reads has the the ERR* name not the sample name in the general stats
    - [ ] We still have the bracken entries in the general stats that we need to turn off
    - [ ] Porechop plots all say 'not able to plot data'

          ```
          [2023-01-20 18:53:22,590] multiqc.plots.bargraph                             [WARNING]  Tried to make bar plot, but had no data: porechop-starttrim-barplot
          [2023-01-20 18:53:22,590] multiqc.plots.bargraph                             [WARNING]  Tried to make bar plot, but had no data: porechop-endtrim-barplot
          [2023-01-20 18:53:22,590] multiqc.plots.bargraph                             [WARNING]  Tried to make bar plot, but had no data: porechop-middlesplit-barplot
          ```
- [ ] I agree with @Midnighter that  we need a separate MQC report for Nanopore data, but I don't want to mess with pipeline code atm and focus on bug fixing (separate issue: #218 )
- [ ] We only picked up the Bracken results, and no Kraken2 etc. for some reason (I guess the file names we used wasn't correct )

Output files:

- [ ] Centrifuge ran despite no multiQC report, however `.results.txt` files in that directory are empty
- [ ] Kaiju is a complete fail, no output!
- [ ] MetaPhlan3 runs fine for short-reads, but all long reads fail with 100% unknown, maybe we should filter this out (I suspect long-reads are unsuitable because long-reads trying to be mapped against short genes witha s hort read aligner )
- [ ] mOTUs did not execute because when supplying in TAR not accounted for [here](https://github.com/nf-core/taxprofiler/blob/d3bad1d720f0dda53e877457c6e653ab4b4b83ca/subworkflows/local/db_check.nf#L44)

Overall we get 35% reads classified with Brakcken so I think this  a good sign this is reasonable dataset

**Comment by jfy133** [comment]
- [ ] Add to docs we _recommend_ running SR/LR separtely (although running together _is_ supported)

**Comment by sofstam** [comment]
Shall we close this?

**Comment by jfy133** [comment]
Not yet, lets get the samplesheets and databases seets upload to test-datasets and then we can close it :)
