### ISSUE TITLE
Remove support for uncompressed fastq files from check_samplesheet.py and docs

### ISSUE THREAD

**Issue by watsonar** [nf-core/taxprofiler#87]
### Description of the bug

`check_samplesheet.py` allows the input of uncompressed fastq files into the workflow, but these files are not supported by the kraken2 module (even when the `--gzip-compressed` flag is removed) and an error is produced at the kraken2 profiling step. Thanks for all your help on the Slack!

### System information

- Nextflow version: 22.04.3.5703
- Hardware: AWS EC2 instance r5a.8xlarge with gp3 volume
- Executor: local
- Container engine: Singularity
- OS: Ubuntu 22.04 LTS
- Version of nf-core/taxprofiler: dev

**Comment by jfy133** [comment]
Done in: https://github.com/nf-core/taxprofiler/commit/ec13b8d608c5a95e9a2e27ae6c2b76691d5b0448
